# Generated by Django 3.0.4 on 2020-03-06 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MassEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Mass Email to all Member',
                'verbose_name_plural': 'Mass Email',
            },
        ),
    ]
