# Generated by Django 3.1.1 on 2020-10-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200902_0922'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailListEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'unique_together': {('email',)},
            },
        ),
    ]
