# Generated by Django 3.1.1 on 2020-10-11 18:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_emaillistentry_email_confirmed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='massemail',
            options={'verbose_name': 'Mass Email', 'verbose_name_plural': 'Mass Email'},
        ),
        migrations.AddField(
            model_name='emaillistentry',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='sign up date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emaillistentry',
            name='receive_test_emails',
            field=models.BooleanField(default=False, verbose_name='receive tests'),
        ),
        migrations.AddField(
            model_name='massemail',
            name='sent',
            field=models.BooleanField(default=False, help_text='Has the message been sent out?', verbose_name='sent'),
        ),
        migrations.AlterField(
            model_name='massemail',
            name='message',
            field=models.TextField(help_text='Enter the body of the email. Can include html tags such as <br> and <img>', verbose_name='email message'),
        ),
        migrations.AlterField(
            model_name='massemail',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='email subject line'),
        ),
    ]
