# Generated by Django 3.0 on 2020-01-14 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="What is the team member's name?", max_length=150, verbose_name='team member name')),
                ('picture', models.FileField(help_text='Upload team member image.', upload_to='team_images', verbose_name="member's picture")),
                ('role', models.CharField(help_text="What is the team member's role?", max_length=150, verbose_name='team member role')),
                ('category', models.CharField(choices=[('CURRENT', 'Current Member'), ('PAST', 'Past Member'), ('AFFILIATE', 'Affiliate')], default='CURRENT', help_text="What is the member's category?", max_length=20, verbose_name='member type')),
                ('link', models.URLField(blank=True, help_text="What is member's web page?", null=True, verbose_name='team member web page URL')),
            ],
        ),
    ]
