# Generated by Django 3.1.4 on 2020-12-09 15:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='What is the department name (e.g. CGA)?', max_length=150, verbose_name='department')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='What is the organization name (e.g. NCSU, APHIS)?', max_length=150, verbose_name='team member organization')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="What is the team member's first name?", max_length=150, null=True, verbose_name='first name')),
                ('last_name', models.CharField(help_text="What is the team member's last/family name?", max_length=150, null=True, verbose_name='last name')),
                ('picture', models.FileField(help_text='Upload team member image.', null=True, upload_to='team_images', verbose_name="team member's picture")),
                ('role', models.CharField(help_text="What is the team member's role in the project?", max_length=250, null=True, verbose_name='team member role')),
                ('title', models.CharField(help_text="What is the team member's title (e.g. Graduate Student, Research Associate, etc.)?", max_length=100, null=True, verbose_name='team member title')),
                ('category', models.CharField(choices=[('CURRENT', 'Current Member'), ('PAST', 'Past Member'), ('AFFILIATE', 'Affiliate')], default='CURRENT', help_text="What is the member's category?", max_length=20, null=True, verbose_name='member type')),
                ('link', models.URLField(blank=True, help_text="What is member's web page?", null=True, verbose_name='team member web page URL')),
                ('github', models.URLField(blank=True, help_text="What is member's GitHub URL?", null=True, verbose_name='team member github URL')),
                ('rank', models.PositiveSmallIntegerField(blank=True, default=2, help_text='relative position in the member list (1 - top of list, 10 - bottom of list). If 2 members have same rank, they will then be sorted by most recently changed.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='relative position in the member list')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.department', verbose_name='department')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.organization', verbose_name='organization')),
            ],
        ),
    ]
