# Generated by Django 3.0 on 2020-01-17 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20200115_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(help_text='What is the department name (e.g. CGA)?', max_length=150, verbose_name='department'),
        ),
        migrations.AlterField(
            model_name='member',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.Department', verbose_name='department'),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(help_text="What is the team member's first name?", max_length=150, null=True, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(help_text="What is the team member's last/family name?", max_length=150, null=True, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='title',
            field=models.CharField(help_text="What is the team member's title (e.g. Graduate Student, Research Associate, etc.)?", max_length=100, null=True, verbose_name='team member title'),
        ),
    ]
