# Generated by Django 3.0 on 2020-01-18 20:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_auto_20200118_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='rank',
            field=models.PositiveSmallIntegerField(blank=True, default=2, help_text='relative position in the member list (1 - top of list, 10 - bottom of list). If 2 members have same rank, they will then be sorted by most recently changed.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='relative position in the member list'),
        ),
    ]
