# Generated by Django 3.1.4 on 2020-12-09 15:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import pops.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Give your case study a descriptive name.', max_length=150, verbose_name='case study name')),
                ('description', models.TextField(blank=True, help_text='Give your case study a description.', max_length=300, null=True, verbose_name='case study description')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('number_of_pests', models.PositiveSmallIntegerField(blank=True, default=1, help_text='How many pests are in your model system?', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='number of pests')),
                ('number_of_hosts', models.PositiveSmallIntegerField(blank=True, default=1, help_text='How many hosts are in your model system?', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='number of hosts')),
                ('start_year', models.PositiveSmallIntegerField(blank=True, default=2012, help_text='The first year that you have pest occurence data for calibration.', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2200)], verbose_name='first calibration year')),
                ('end_year', models.PositiveSmallIntegerField(blank=True, default=2018, help_text='The last year that you have pest occurence data for calibration.', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2200)], verbose_name='final calibration year')),
                ('future_years', models.PositiveSmallIntegerField(blank=True, default=2023, help_text='The last year that you want to run the PoPS model (this is in the future).', validators=[django.core.validators.MinValueValidator(2018), django.core.validators.MaxValueValidator(2200)], verbose_name='final model year')),
                ('time_step', models.CharField(choices=[('month', 'Month'), ('week', 'Week'), ('day', 'Day')], default='Month', help_text='Select a time step for your simulation:', max_length=50, verbose_name='time step')),
                ('staff_approved', models.BooleanField(default=False, help_text='Sample help text.', verbose_name='approved by staff')),
                ('calibration_status', models.CharField(blank=True, choices=[('NO START', 'Not started'), ('IN PROGRESS', 'In progress'), ('FAILED', 'Failed'), ('SUCCESS', 'Successful'), ('EXTERNAL', 'Non-self')], default='NO START', help_text='What type of model do you want to use?', max_length=20, verbose_name='calibration status')),
                ('use_external_calibration', models.BooleanField(default=False, help_text='Sample help text.', verbose_name="use another case study's calibration?")),
                ('model_api', models.CharField(blank=True, help_text='Link to the model api for this case study.', max_length=250, null=True, verbose_name='model api url')),
                ('calibration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pops.casestudy', verbose_name='calibrated case study')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'case study',
                'verbose_name_plural': 'case studies',
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text="What is the host's common name?", max_length=150, verbose_name='host common name')),
                ('score', models.DecimalField(blank=True, decimal_places=2, default=1, help_text='Host score is a value between 0 and 1. 0 has no effect while 1 has maximum effect. This is for generalist pests with differing host preferences and pathogens with differing host competencies.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='score')),
                ('mortality_on', models.BooleanField(blank=True, help_text='Does the host experience mortality as a result of the pest/pathogen?', verbose_name='mortality')),
                ('case_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pops.casestudy', verbose_name='case study')),
            ],
            options={
                'verbose_name': 'host',
                'verbose_name_plural': 'hosts',
            },
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('number_infected', models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='number_infected')),
                ('infected_area', models.DecimalField(blank=True, decimal_places=2, default=1, help_text='Overall infected area from the run.', max_digits=16, validators=[django.core.validators.MinValueValidator(0)], verbose_name='infected_area (m^2)')),
                ('year', models.PositiveIntegerField(default=2020, null=True, validators=[django.core.validators.MinValueValidator(2018)], verbose_name='year')),
                ('single_spread_map', models.JSONField(null=True)),
                ('probability_map', models.JSONField(null=True)),
                ('susceptible_map', models.JSONField(null=True)),
                ('escape_probability', models.DecimalField(blank=True, decimal_places=2, default=1, help_text='Probability that the pest/pathogen escapes quarantine or other boundary.', max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='probability of escape')),
            ],
            options={
                'verbose_name': 'output',
                'verbose_name_plural': 'outputs',
            },
        ),
        migrations.CreateModel(
            name='Pest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='What is the common name of the pest/pathogen?', max_length=150, null=True, verbose_name='pest common name')),
                ('use_treatment', models.BooleanField(default=False, help_text='Has management occurred during the time of initial infection/infestation?', verbose_name='prior treatments')),
                ('vector_born', models.BooleanField(default=False, help_text='Is the disease spread by a vector (e.g. an insect)?', verbose_name='vector born')),
                ('model_type', models.CharField(blank=True, choices=[('SI', 'Susceptible Infected'), ('SID', 'Susceptible Infected Diseased'), ('SEID', 'Susceptible Exposed Infected Diseased')], default='SI', help_text='What type of model do you want to use?', max_length=20, verbose_name='model type')),
                ('natural_dispersal_type', models.CharField(blank=True, choices=[('CAUCHY', 'Cauchy'), ('DOUBLE SCALE CAUCHY', 'Double Scale Cauchy'), ('EXPONENTIAL', 'Exponential'), ('DOUBLE SCALE EXPONENTIAL', 'Double Scale Exponential')], default='CAUCHY', max_length=70, verbose_name='natural dispersal type')),
                ('anthropogenic_dispersal_type', models.CharField(blank=True, choices=[('CAUCHY', 'Cauchy'), ('DOUBLE SCALE CAUCHY', 'Double Scale Cauchy'), ('EXPONENTIAL', 'Exponential'), ('DOUBLE SCALE EXPONENTIAL', 'Double Scale Exponential')], default='CAUCHY', max_length=70, verbose_name='anthropogenic dispersal type')),
                ('case_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pops.casestudy', verbose_name='case study')),
            ],
            options={
                'verbose_name': 'pest',
                'verbose_name_plural': 'pests',
            },
        ),
        migrations.CreateModel(
            name='PestInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=150, verbose_name='pest common name')),
                ('scientific_name', models.CharField(help_text='Sample help text.', max_length=150, verbose_name='pest scientific name')),
                ('about', models.TextField(help_text='Sample help text.', verbose_name='about the pest')),
                ('risks', models.TextField(help_text='Sample help text.', verbose_name='risks associated with the pest')),
                ('management_activity', models.TextField(help_text='Sample help text.', verbose_name='management activities to control the pest')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('staff_approved', models.BooleanField(default=False, help_text='Sample help text.', verbose_name='approved by staff')),
                ('invasive', models.BooleanField(default=True, help_text='Is the organism invasive in the US?', verbose_name='invasive')),
                ('host_type', models.CharField(choices=[('ANIMAL', 'Animal'), ('PLANT', 'Plant')], default='PLANT', help_text='Choose what system type this pest/pathogen infects.', max_length=30, verbose_name='host type')),
                ('organism_type', models.CharField(choices=[('PEST', 'Pest (e.g. insect)'), ('PATHOGEN', 'Pathogen (e.g. disease)')], default='PEST', help_text='Choose whether this is a pest or pathogen.', max_length=30, verbose_name='organism type')),
                ('arrival_year', models.PositiveSmallIntegerField(blank=True, default=None, help_text='The first year that it was identified in the US.', null=True, validators=[django.core.validators.MinValueValidator(1700), django.core.validators.MaxValueValidator(2100)], verbose_name='first year found in US')),
                ('arrival_location', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='first location found in US (State)')),
                ('thumbnail', models.FileField(blank=True, help_text='Upload thumbnail image of pest/pathogen (58x58 px crop to 0.8in square at 72ppi).', null=True, upload_to='pest_images', verbose_name='Small thumbnail image of pest/pathogen')),
                ('large_image', models.FileField(blank=True, help_text='Upload image of pest/pathogen (crop to 2in square at 72ppi).', null=True, upload_to='pest_images', verbose_name='Large image of pest/pathogen')),
                ('spread_image', models.FileField(blank=True, help_text='Upload image or gif of pest/pathogen ( at 72ppi).', null=True, upload_to='pest_images', verbose_name='Image or GIF of forecast')),
            ],
            options={
                'verbose_name': 'pest information',
                'verbose_name_plural': 'pest informations',
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('IN PROGRESS', 'In progress'), ('READING DATA', 'Reading data'), ('WAITING FOR TL', 'Waiting for Tangible Landscape'), ('RUNNING MODEL', 'Running model'), ('WRITING DATA', 'Writing data'), ('FAILED', 'Failed'), ('SUCCESS', 'Successful')], default='PENDING', max_length=20, verbose_name='run status')),
                ('management_polygons', models.JSONField(blank=True, null=True)),
                ('management_cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='management cost')),
                ('management_area', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='management area')),
                ('logging', models.TextField(blank=True, help_text='For checking error logs for backend model runs', max_length=300, null=True, verbose_name='error logs for backend')),
                ('time_taken', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='time taken')),
                ('steering_year', models.PositiveIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(2018)], verbose_name='steering year')),
            ],
            options={
                'verbose_name': 'run',
                'verbose_name_plural': 'runs',
            },
        ),
        migrations.CreateModel(
            name='AllPlantsData',
            fields=[
                ('case_study', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pops.casestudy', verbose_name='case study')),
                ('user_file', models.FileField(blank=True, help_text='Upload your total plants data as a raster file. This could be all the plants in a cell or all cells could have the value of the maximum number of hosts foound in any cell in your study area.', upload_to=pops.models.all_plants_directory, verbose_name='all plant data')),
            ],
            options={
                'verbose_name': 'all_plant',
                'verbose_name_plural': 'all_plants',
            },
        ),
        migrations.CreateModel(
            name='AnthropogenicDirection',
            fields=[
                ('pest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pops.pest', verbose_name='pest')),
                ('direction', models.CharField(choices=[('N', 'North'), ('NE', 'Northeast'), ('E', 'East'), ('SE', 'Southeast'), ('S', 'South'), ('SW', 'Southwest'), ('W', 'West'), ('NW', 'Northwest')], default='N', help_text='What is the predominate anthropogenic direction in your study area?', max_length=30, verbose_name='anthropogenic direction')),
                ('kappa', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], default=1, help_text='What is the average anthropogenic strength in your study area? 0 is no effect and 12 is very strong directional movement', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='anthropogenic direction strenth (kappa)')),
            ],
            options={
                'verbose_name': 'anthropogenic direction',
                'verbose_name_plural': 'anthropogenic directions',
            },
        ),
        migrations.CreateModel(
            name='CalibrationInfestation',
            fields=[
                ('pest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pops.pest', verbose_name='pest')),
                ('user_file', models.FileField(blank=True, help_text='Upload your calibration infestation/infection data as a raster file (1 file with a layer for each year). At least 3 years are needed for calibration and validation ', upload_to=pops.models.validation_infestation_directory, verbose_name='calibration infestation data')),
            ],
            options={
                'verbose_name': 'calibration_infestation_data',
                'verbose_name_plural': 'calibration_infestation_datas',
            },
        ),
        migrations.CreateModel(
            name='DistanceToBoundary',
            fields=[
                ('output', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pops.output', verbose_name='output')),
                ('west_distance', models.DecimalField(blank=True, decimal_places=2, help_text='Spread rate in westerly direction', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='westerly distance to boundary')),
                ('east_distance', models.DecimalField(blank=True, decimal_places=2, help_text='Spread rate in easterly direction', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='easterly distance to boundary')),
                ('north_distance', models.DecimalField(blank=True, decimal_places=2, help_text='Spread rate in northerly direction', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='northerly distance to boundary')),
                ('south_distance', models.DecimalField(blank=True, decimal_places=2, help_text='Spread rate in southerly direction', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='southerly distance to boundary')),
            ],
            options={
                'verbose_name': 'distance to boundary',
                'verbose_name_plural': 'distance to boundarys',
            },
        ),
        migrations.CreateModel(
            name='HostData',
            fields=[
                ('host', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pops.host', verbose_name='host')),
                ('user_file', models.FileField(blank=True, help_text='Upload your host data as a raster file.', upload_to=pops.models.host_directory, verbose_name='host data')),
                ('host_map', models.JSONField(null=True)),
            ],
            options={
                'verbose_name': 'host_data',
                'verbose_name_plural': 'hosts_data',
            },
        ),
        migrations.CreateModel(
            name='InitialInfestation',
            fields=[
                ('pest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pops.pest', verbose_name='pest')),
                ('user_file', models.FileField(blank=True, help_text='Upload your initial infestation/infection data as a raster file (1 file with a layer for each year). At least 3 years are needed for calibration and validation ', upload_to=pops.models.initial_infestation_directory, verbose_name='initial infestation data')),
            ],
            options={
                'verbose_name': 'initial_infestation_data',
                'verbose_name_plural': 'initial_infestation_datas',
            },
        ),
        migrations.CreateModel(
            name='MapBoxParameters',
            fields=[
                ('case_study', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pops.casestudy', verbose_name='case study')),
                ('longitude', models.DecimalField(blank=True, decimal_places=14, default=-75.89533170441632, help_text='Longitude of the center of the case study', max_digits=17, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='longitude')),
                ('latitude', models.DecimalField(blank=True, decimal_places=14, default=40.2039152196177, help_text='Latitude of the center of the case study', max_digits=17, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='latitude')),
                ('zoom', models.PositiveSmallIntegerField(blank=True, default=7, help_text='The zoom level of MapBox.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(16)], verbose_name='mapbox zoom level')),
            ],
            options={
                'verbose_name': 'map box parameter',
                'verbose_name_plural': 'map box parameters',
            },
        ),
        migrations.CreateModel(
            name='Mortality',
            fields=[
                ('host', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pops.host', verbose_name='host')),
                ('method', models.CharField(choices=[('DATA_FILE', 'PoPS estimates mortality rate and time lag from user data'), ('USER', 'User provides mortality rate and time lag')], default='DATA_FILE', help_text='Choose a method to determine mortality rate and time lag.', max_length=30, verbose_name='mortality rate method')),
                ('user_file', models.FileField(blank=True, help_text='A single raster file with number of trees that experienced mortality as a result of the pest/pathogen that year (each layer is a year)', null=True, upload_to=pops.models.mortality_directory, verbose_name='mortality data')),
                ('rate', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='What percentage of hosts experience mortality each year from the pest or pathogen?', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='mortality rate (fraction)')),
                ('time_lag', models.PositiveSmallIntegerField(blank=True, default=2, help_text='How long after initial infection/infestation (in years) before mortality occurs on average?', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='mortality time lag (years)')),
            ],
            options={
                'verbose_name': 'mortality',
                'verbose_name_plural': 'mortalities',
            },
        ),
        migrations.CreateModel(
            name='PriorTreatment',
            fields=[
                ('pest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pops.pest', verbose_name='pest')),
                ('user_file', models.FileField(blank=True, help_text='Upload the raster file for management actions. 1 file with a layer for each year.', null=True, upload_to=pops.models.treatment_directory, verbose_name='prior treatments data')),
            ],
            options={
                'verbose_name': 'prior_treatment',
                'verbose_name_plural': 'prior_treatments',
            },
        ),
        migrations.CreateModel(
            name='SpreadRate',
            fields=[
                ('output', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pops.output', verbose_name='output')),
                ('west_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Spread rate in westerly direction', max_digits=16, null=True, verbose_name='westerly spread rate')),
                ('east_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Spread rate in easterly direction', max_digits=16, null=True, verbose_name='easterly spread rate')),
                ('north_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Spread rate in northerly direction', max_digits=16, null=True, verbose_name='northerly spread rate')),
                ('south_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Spread rate in southerly direction', max_digits=16, null=True, verbose_name='southerly spread rate')),
            ],
            options={
                'verbose_name': 'spread rate',
                'verbose_name_plural': 'spread rates',
            },
        ),
        migrations.CreateModel(
            name='TimeToBoundary',
            fields=[
                ('output', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pops.output', verbose_name='output')),
                ('west_time', models.DecimalField(blank=True, decimal_places=2, help_text='Spread rate in westerly direction', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='westerly time to boundary')),
                ('east_time', models.DecimalField(blank=True, decimal_places=2, help_text='Spread rate in easterly direction', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='easterly time to boundary')),
                ('north_time', models.DecimalField(blank=True, decimal_places=2, help_text='Spread rate in northerly direction', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='northerly time to boundary')),
                ('south_time', models.DecimalField(blank=True, decimal_places=2, help_text='Spread rate in southerly direction', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='southerly time to boundary')),
            ],
            options={
                'verbose_name': 'time to boundary',
                'verbose_name_plural': 'time to boundarys',
            },
        ),
        migrations.CreateModel(
            name='ValidationInfestation',
            fields=[
                ('pest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pops.pest', verbose_name='pest')),
                ('user_file', models.FileField(blank=True, help_text='Upload your validation infestation/infection data as a raster file (1 file with a layer for each year). At least 3 years are needed for calibration and validation ', upload_to=pops.models.calibration_infestation_directory, verbose_name='validation infestation data')),
            ],
            options={
                'verbose_name': 'validation_infestation_data',
                'verbose_name_plural': 'validation_infestation_datas',
            },
        ),
        migrations.CreateModel(
            name='Vector',
            fields=[
                ('pest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pops.pest', verbose_name='pest')),
                ('common_name', models.CharField(blank=True, help_text='What is the common name of the vector?', max_length=150, verbose_name='vector common name')),
                ('scientific_name', models.CharField(blank=True, help_text='What is the scientific name of the vector?', max_length=150, verbose_name='vector scientific name')),
                ('user_file', models.FileField(blank=True, help_text='Upload your vector data as a raster file.', null=True, upload_to=pops.models.vector_directory, verbose_name='vector data')),
            ],
            options={
                'verbose_name': 'vector',
                'verbose_name_plural': 'vectors',
            },
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('case_study', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pops.casestudy', verbose_name='case study')),
                ('wind_on', models.BooleanField(default=False, help_text='Does wind strongly affect the spread of your pest/pathogen and do you have a predominate wind direction and strength?', verbose_name='wind')),
                ('seasonality_on', models.BooleanField(default=False, help_text='Does your pest/pathogen not spread during part of the year?', verbose_name='seasonality')),
                ('lethal_temp_on', models.BooleanField(default=False, help_text='Does your pest/pathogen experience mortality due to extreme temperature conditions?', verbose_name='lethal temperature')),
                ('temp_on', models.BooleanField(default=False, help_text='Does temperature affect the reproduction and survival of your pest/pathogen?', verbose_name='temperature')),
                ('precipitation_on', models.BooleanField(default=False, help_text='Does precipitation affect the reproduction and survival of your pest/pathogen?', verbose_name='precipitation')),
            ],
            options={
                'verbose_name': 'weather',
                'verbose_name_plural': 'weathers',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('name', models.CharField(help_text='Give your session a descriptive name.', max_length=150, verbose_name='session name')),
                ('description', models.TextField(blank=True, help_text='Give your session a description.', max_length=300, null=True, verbose_name='session description')),
                ('reproductive_rate', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Reproductive rate of pest/pathogen', max_digits=6, null=True, verbose_name='reproductive rate')),
                ('distance_scale', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='distance scale')),
                ('final_year', models.PositiveIntegerField(default=2021, null=True, validators=[django.core.validators.MinValueValidator(2018)], verbose_name='final run year')),
                ('management_month', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=7, help_text='What month does management take place?', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='month management takes place')),
                ('weather', models.CharField(blank=True, choices=[('BAD', 'Poor spread conditions'), ('AVERAGE', 'Average spread conditions'), ('GOOD', 'Optimal spread conditions')], default='AVERAGE', max_length=20, verbose_name='weather')),
                ('max_value', models.PositiveSmallIntegerField(blank=True, default=0, help_text='Maximum value of number of infected in a cell for final year of the default run', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='maximum value within a cell in default run')),
                ('public', models.BooleanField(default=False, help_text='Is the session sharing set to public (any user can view and edit the session)?', verbose_name='public')),
                ('case_study', models.ForeignKey(help_text='Select a case study for this session.', on_delete=django.db.models.deletion.CASCADE, to='pops.casestudy', verbose_name='case study')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('default_run', models.OneToOneField(blank=True, help_text='Default no management run for this session and default run_collection parameters.', null=True, on_delete=django.db.models.deletion.CASCADE, to='pops.run', verbose_name='default run')),
            ],
            options={
                'verbose_name': 'session',
                'verbose_name_plural': 'sessions',
            },
        ),
        migrations.CreateModel(
            name='RunCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default_name', max_length=45, verbose_name='run name')),
                ('description', models.TextField(blank=True, default='Give your run a description.', help_text='Give your run a description.', max_length=300, null=True, verbose_name='run description')),
                ('random_seed', models.PositiveIntegerField(default=33, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='random seed')),
                ('tangible_landscape', models.BooleanField(default=False, help_text='Use tangible landscape for management?', verbose_name='tangible landscape')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('IN PROGRESS', 'In progress'), ('READING DATA', 'Reading data'), ('WAITING FOR TL', 'Waiting for Tangible Landscape'), ('RUNNING MODEL', 'Running model'), ('WRITING DATA', 'Writing data'), ('FAILED', 'Failed'), ('SUCCESS', 'Successful')], default='PENDING', max_length=20, verbose_name='run status')),
                ('budget', models.PositiveIntegerField(default=30000000, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='budget')),
                ('default', models.BooleanField(default=False, help_text='Is this the default run collection for this session?', verbose_name='default run collection')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pops.session', verbose_name='session id')),
            ],
            options={
                'verbose_name': 'run collection',
                'verbose_name_plural': 'run collections',
            },
        ),
        migrations.AddField(
            model_name='run',
            name='run_collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pops.runcollection', verbose_name='run collection id'),
        ),
        migrations.CreateModel(
            name='ReproductiveRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=1, max_digits=5, verbose_name='reproductive rate value')),
                ('probability', models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='reproductive rate probability')),
                ('pest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pops.pest', verbose_name='pest')),
            ],
            options={
                'verbose_name': 'reproductive rate',
                'verbose_name_plural': 'reproductive rates',
            },
        ),
        migrations.AddField(
            model_name='pest',
            name='pest_information',
            field=models.ForeignKey(blank=True, help_text='Sample help text.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pops.pestinformation', verbose_name='pest information'),
        ),
        migrations.CreateModel(
            name='PercentNaturalDistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='percent natural distance scale value')),
                ('probability', models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='percent natural distance scale probability')),
                ('pest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pops.pest', verbose_name='pest')),
            ],
            options={
                'verbose_name': 'natural distance dispersal percentage',
                'verbose_name_plural': 'natural distance dispersal percentages',
            },
        ),
        migrations.AddField(
            model_name='output',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pops.run', verbose_name='run id'),
        ),
        migrations.CreateModel(
            name='NaturalDistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=0, max_digits=5, verbose_name='natural distance scale value')),
                ('probability', models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='natural distance scale probability')),
                ('pest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pops.pest', verbose_name='pest')),
            ],
            options={
                'verbose_name': 'natural distance dispersal',
                'verbose_name_plural': 'natural distance dispersals',
            },
        ),
        migrations.CreateModel(
            name='InfectedToDiseased',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=0, max_digits=5, verbose_name='infected to diseased value')),
                ('probability', models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='infected to diseased  probability')),
                ('pest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pops.pest', verbose_name='pest')),
            ],
            options={
                'verbose_name': 'infected to diseased',
                'verbose_name_plural': 'infected to diseaseds',
            },
        ),
        migrations.CreateModel(
            name='HistoricData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=2015, null=True, validators=[django.core.validators.MinValueValidator(1900)], verbose_name='year')),
                ('data', models.JSONField(null=True)),
                ('infected_area', models.DecimalField(blank=True, decimal_places=2, default=1, help_text='Overall infected area from the run.', max_digits=16, validators=[django.core.validators.MinValueValidator(0)], verbose_name='infected_area (m^2)')),
                ('number_infected', models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='number_infected')),
                ('case_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pops.casestudy', verbose_name='case study id')),
            ],
            options={
                'verbose_name': 'historic data',
                'verbose_name_plural': 'historic datas',
            },
        ),
        migrations.CreateModel(
            name='CrypticToInfected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=0, max_digits=5, verbose_name='cryptic to infected value')),
                ('probability', models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='cryptic to infected  probability')),
                ('pest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pops.pest', verbose_name='pest')),
            ],
            options={
                'verbose_name': 'cryptic to infected',
                'verbose_name_plural': 'cryptic to infecteds',
            },
        ),
        migrations.CreateModel(
            name='Creation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pops.host', verbose_name='host')),
            ],
            options={
                'verbose_name': 'creation of host map',
                'verbose_name_plural': 'creation of host maps',
            },
        ),
        migrations.CreateModel(
            name='AnthropogenicDistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=0, max_digits=5, verbose_name='anthropogenic distance scale value')),
                ('probability', models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='anthropogenic distance scale probability')),
                ('pest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pops.pest', verbose_name='pest')),
            ],
            options={
                'verbose_name': 'anthropogenic distance dispersal',
                'verbose_name_plural': 'anthropogenic distance dispersals',
            },
        ),
        migrations.CreateModel(
            name='AllowedUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pops.session', verbose_name='session id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user id')),
            ],
            options={
                'verbose_name': 'allowed user',
                'verbose_name_plural': 'allowed users',
            },
        ),
        migrations.CreateModel(
            name='LethalTemperature',
            fields=[
                ('weather', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pops.weather', verbose_name='weather')),
                ('lethal_type', models.CharField(choices=[('COLD', 'Cold'), ('HOT', 'Hot')], default='COLD', help_text='Is your pest killed by hot or cold temperatures?', max_length=4, verbose_name='lethal temperature type')),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1, help_text='What month does your lethal temperature occur?', verbose_name='month in which lethal temperature occurs')),
                ('value', models.DecimalField(blank=True, decimal_places=2, help_text='What is the lethal temperature at which pest/pathogen mortality occurs?', max_digits=4, validators=[django.core.validators.MinValueValidator(-50), django.core.validators.MaxValueValidator(50)], verbose_name='lethal temperature')),
                ('lethal_temperature_data', models.FileField(help_text='Upload your letah temperature data as a raster file (1 file with a layer for each year).', null=True, upload_to=pops.models.lethal_temperature_directory, verbose_name='lethal temperature data')),
            ],
            options={
                'verbose_name': 'lethal temperature',
                'verbose_name_plural': 'lethal temperatures',
            },
        ),
        migrations.CreateModel(
            name='Precipitation',
            fields=[
                ('weather', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pops.weather', verbose_name='weather')),
                ('method', models.CharField(choices=[('RECLASS', 'Reclass'), ('POLYNOMIAL', 'Polynomial')], default='RECLASS', help_text='Choose a method to transform precipitation into a coefficient used by the model. Precipitation values are transformed into a value between 0 and 1.', max_length=30, verbose_name='precipitation coefficient creation method')),
                ('precipitation_data', models.FileField(help_text='Upload your precipitation data as a raster file (1 file with a layer for each timestep).', null=True, upload_to=pops.models.precipitation_directory, verbose_name='precipitation data')),
            ],
            options={
                'verbose_name': 'precipitation',
                'verbose_name_plural': 'precipitations',
            },
        ),
        migrations.CreateModel(
            name='Seasonality',
            fields=[
                ('weather', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pops.weather', verbose_name='weather')),
                ('first_month', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1, help_text='What is the first month your pest/pathogen spreads during the year?', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='first month of season')),
                ('last_month', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=12, help_text='What is the last month your pest/pathogen spreads during the year?', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='last month of season')),
            ],
            options={
                'verbose_name': 'seasonality',
                'verbose_name_plural': 'seasonalities',
            },
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('weather', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pops.weather', verbose_name='weather')),
                ('method', models.CharField(choices=[('RECLASS', 'Reclass'), ('POLYNOMIAL', 'Polynomial')], default='RECLASS', help_text='Choose a method to transform temperature into a coefficient used by the model. Temperature values are transformed into a value between 0 and 1.', max_length=30, verbose_name='temperature coefficient creation method')),
                ('temperature_data', models.FileField(help_text='Upload your temperature data as a raster file (1 file with a layer for each timestep).', null=True, upload_to=pops.models.temperature_directory, verbose_name='temperature data')),
            ],
            options={
                'verbose_name': 'temperature',
                'verbose_name_plural': 'temperatures',
            },
        ),
        migrations.CreateModel(
            name='Wind',
            fields=[
                ('weather', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pops.weather', verbose_name='weather')),
                ('wind_direction', models.CharField(choices=[('N', 'North'), ('NE', 'Northeast'), ('E', 'East'), ('SE', 'Southeast'), ('S', 'South'), ('SW', 'Southwest'), ('W', 'West'), ('NW', 'Northwest')], default='N', help_text='What is the predominate wind direction in your study area?', max_length=30, verbose_name='wind direction')),
                ('kappa', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], default=1, help_text='What is the average wind strength in your study area? 0 is no effect and 12 is very strong directional movement', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='wind strenth (kappa)')),
            ],
            options={
                'verbose_name': 'wind',
                'verbose_name_plural': 'winds',
            },
        ),
        migrations.CreateModel(
            name='VectorReproductiveRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=1, max_digits=5, verbose_name='vector reproductive rate value')),
                ('probability', models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='vector reproductive rate probability')),
                ('vector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pops.vector', verbose_name='vector')),
            ],
            options={
                'verbose_name': 'vector reproductive rate',
                'verbose_name_plural': 'vector reproductive rates',
            },
        ),
        migrations.CreateModel(
            name='VectorNaturalDistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=0, max_digits=5, verbose_name='vector natural distance scale value')),
                ('probability', models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='vector natural distance scale probability')),
                ('vector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pops.vector', verbose_name='vector')),
            ],
            options={
                'verbose_name': 'vector natural distance dispersal',
                'verbose_name_plural': 'vector natural distance dispersals',
            },
        ),
        migrations.CreateModel(
            name='VectorHostTransmissionRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=0, max_digits=5, verbose_name='vector to host transmission rate value')),
                ('probability', models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='vector to host transmission rate probability')),
                ('vector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pops.vector', verbose_name='vector')),
            ],
            options={
                'verbose_name': 'vector to host transmission rate',
                'verbose_name_plural': 'vector to host transmission rates',
            },
        ),
        migrations.CreateModel(
            name='PriorTreatmentYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2200)], verbose_name='prior treatment year')),
                ('prior_treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pops.priortreatment', verbose_name='prior treatment')),
            ],
            options={
                'verbose_name': 'prior treatment year',
                'verbose_name_plural': 'prior treatment years',
            },
        ),
        migrations.CreateModel(
            name='MortalityTimeLag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=0, max_digits=5, verbose_name='mortality time lag value')),
                ('probability', models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='mortality time lag probability')),
                ('mortality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pops.mortality', verbose_name='mortality')),
            ],
            options={
                'verbose_name': 'mortality time lag',
                'verbose_name_plural': 'mortality time lags',
            },
        ),
        migrations.CreateModel(
            name='MortalityRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=0, max_digits=5, verbose_name='mortality rate value')),
                ('probability', models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='mortality rate probability')),
                ('mortality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pops.mortality', verbose_name='mortality')),
            ],
            options={
                'verbose_name': 'mortality rate',
                'verbose_name_plural': 'mortality rates',
            },
        ),
        migrations.CreateModel(
            name='HostVectorTransmissionRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=0, max_digits=5, verbose_name='host to vector transmission rate value')),
                ('probability', models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='host to vector transmission rate probability')),
                ('vector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pops.vector', verbose_name='vector')),
            ],
            options={
                'verbose_name': 'host to vector transmission rate',
                'verbose_name_plural': 'host to vector transmission rates',
            },
        ),
        migrations.CreateModel(
            name='PrecipitationPolynomial',
            fields=[
                ('precipitation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pops.precipitation', verbose_name='precipitation')),
                ('degree', models.PositiveSmallIntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three')], default=1, help_text='Select the degree of your polynomial function.', verbose_name='polynomial degree')),
                ('a0', models.DecimalField(blank=True, decimal_places=5, help_text='value of a0 in your polynomial transformation.', max_digits=8, null=True, verbose_name='a0')),
                ('a1', models.DecimalField(blank=True, decimal_places=5, help_text='value of a1 in your polynomial transformation.', max_digits=8, null=True, verbose_name='a1')),
                ('a2', models.DecimalField(blank=True, decimal_places=5, help_text='value of a2 in your polynomial transformation.', max_digits=8, null=True, verbose_name='a2')),
                ('a3', models.DecimalField(blank=True, decimal_places=5, help_text='value of a3 in your polynomial transformation.', max_digits=8, null=True, verbose_name='a3')),
                ('x1', models.DecimalField(blank=True, decimal_places=2, help_text='value of x1 in your polynomial transformation.', max_digits=5, null=True, verbose_name='x1')),
                ('x2', models.DecimalField(blank=True, decimal_places=2, help_text='value of x2 in your polynomial transformation.', max_digits=5, null=True, verbose_name='x2')),
                ('x3', models.DecimalField(blank=True, decimal_places=2, help_text='value of x3 in your polynomial transformation.', max_digits=5, null=True, verbose_name='x3')),
            ],
            options={
                'verbose_name': 'precipitation polynomial',
                'verbose_name_plural': 'precipitation polynomials',
            },
        ),
        migrations.CreateModel(
            name='TemperaturePolynomial',
            fields=[
                ('temperature', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pops.temperature', verbose_name='temperature')),
                ('degree', models.PositiveSmallIntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three')], default=1, help_text='Select the degree of your polynomial function.', verbose_name='polynomial degree')),
                ('a0', models.DecimalField(blank=True, decimal_places=5, help_text='value of a0 in your polynomial transformation.', max_digits=8, null=True, verbose_name='a0')),
                ('a1', models.DecimalField(blank=True, decimal_places=5, help_text='value of a1 in your polynomial transformation.', max_digits=8, null=True, verbose_name='a1')),
                ('a2', models.DecimalField(blank=True, decimal_places=5, help_text='value of a2 in your polynomial transformation.', max_digits=8, null=True, verbose_name='a2')),
                ('a3', models.DecimalField(blank=True, decimal_places=5, help_text='value of a3 in your polynomial transformation.', max_digits=8, null=True, verbose_name='a3')),
                ('x1', models.DecimalField(blank=True, decimal_places=2, help_text='value of x1 in your polynomial transformation.', max_digits=5, null=True, verbose_name='x1')),
                ('x2', models.DecimalField(blank=True, decimal_places=2, help_text='value of x2 in your polynomial transformation.', max_digits=5, null=True, verbose_name='x2')),
                ('x3', models.DecimalField(blank=True, decimal_places=2, help_text='value of x3 in your polynomial transformation.', max_digits=5, null=True, verbose_name='x3')),
            ],
            options={
                'verbose_name': 'temperature polynomial',
                'verbose_name_plural': 'temperature polynomials',
            },
        ),
        migrations.CreateModel(
            name='TemperatureReclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum temperature (in degrees Celsius) to reclass from.', max_digits=4, validators=[django.core.validators.MinValueValidator(-50), django.core.validators.MaxValueValidator(100)], verbose_name='min')),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum temperature (in degrees Celsius) to reclass from.', max_digits=4, validators=[django.core.validators.MinValueValidator(-50), django.core.validators.MaxValueValidator(100)], verbose_name='max')),
                ('reclass', models.DecimalField(blank=True, decimal_places=2, help_text='Reclass value (between 0 and 1).', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='reclass')),
                ('temperature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pops.temperature', verbose_name='temperature')),
            ],
            options={
                'verbose_name': 'temperature reclass',
                'verbose_name_plural': 'temperature reclasses',
                'ordering': ['min_value'],
            },
        ),
        migrations.CreateModel(
            name='PrecipitationReclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum precipitation (in millimeters) to reclass from.', max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='min')),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum precipitation (in millimeters) to reclass from.', max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='max')),
                ('reclass', models.DecimalField(blank=True, decimal_places=2, help_text='Reclass value (between 0 and 1).', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='reclass')),
                ('precipitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pops.precipitation', verbose_name='precipitation')),
            ],
            options={
                'verbose_name': 'precipitation reclass',
                'verbose_name_plural': 'precipitation reclasses',
                'ordering': ['min_value'],
            },
        ),
    ]
