# Generated by Django 2.2.4 on 2019-08-08 14:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriorTreatmentYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2200)], verbose_name='prior treatment year')),
                ('prior_treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pops.PriorTreatment', verbose_name='prior treatment')),
            ],
            options={
                'verbose_name': 'prior treatment year',
                'verbose_name_plural': 'prior treatment years',
            },
        ),
        migrations.CreateModel(
            name='MortalityTimeLag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=0, max_digits=5, verbose_name='mortality time lag value')),
                ('probability', models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='mortality time lag probability')),
                ('mortality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pops.Mortality', verbose_name='mortality')),
            ],
            options={
                'verbose_name': 'mortality time lag',
                'verbose_name_plural': 'mortality time lags',
            },
        ),
        migrations.CreateModel(
            name='MortalityRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=0, max_digits=5, verbose_name='mortality rate value')),
                ('probability', models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='mortality rate probability')),
                ('mortality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pops.Mortality', verbose_name='mortality')),
            ],
            options={
                'verbose_name': 'mortality rate',
                'verbose_name_plural': 'mortality rates',
            },
        ),
    ]
