# Generated by Django 2.2.4 on 2019-08-14 13:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='default_run',
            field=models.OneToOneField(blank=True, help_text='Default no management run for this session and default run_collection parameters.', null=True, on_delete=django.db.models.deletion.CASCADE, to='pops.Run', verbose_name='default run'),
        ),
        migrations.AlterField(
            model_name='run',
            name='steering_year',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(2018)], verbose_name='steering year'),
        ),
    ]
