# Generated by Django 2.2.3 on 2019-08-07 14:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0002_auto_20190806_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=14, default=40.2039152196177, help_text='Latitude of the center of the case study', max_digits=17, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=14, default=-75.89533170441632, help_text='Longitude of the center of the case study', max_digits=17, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='longitude'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='zoom',
            field=models.PositiveSmallIntegerField(blank=True, default=7, help_text='The zoom level of MapBox.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(16)], verbose_name='mapbox zoom level'),
        ),
    ]
