# Generated by Django 2.1.5 on 2019-05-24 18:54

from django.db import migrations, models
import django.db.models.deletion
import pops.models


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0002_auto_20190524_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationInfestation',
            fields=[
                ('pest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pops.Pest', verbose_name='pest')),
                ('user_file', models.FileField(blank=True, help_text='Upload your calibration infestation/infection data as a raster file (1 file with a layer for each year). At least 3 years are needed for calibration and validation ', upload_to=pops.models.initial_infestation_directory, verbose_name='calibration infestation data')),
            ],
            options={
                'verbose_name': 'calibration_infestation_data',
                'verbose_name_plural': 'calibration_infestation_datas',
            },
        ),
        migrations.CreateModel(
            name='ValidationInfestation',
            fields=[
                ('pest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pops.Pest', verbose_name='pest')),
                ('user_file', models.FileField(blank=True, help_text='Upload your validation infestation/infection data as a raster file (1 file with a layer for each year). At least 3 years are needed for calibration and validation ', upload_to=pops.models.initial_infestation_directory, verbose_name='validation infestation data')),
            ],
            options={
                'verbose_name': 'validation_infestation_data',
                'verbose_name_plural': 'validation_infestation_datas',
            },
        ),
    ]
