# Generated by Django 3.1.4 on 2021-01-09 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0002_auto_20210107_1448'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clippedhostlocation',
            options={'verbose_name': 'host location - clipped', 'verbose_name_plural': 'host locations - - clipped'},
        ),
        migrations.AlterModelOptions(
            name='clippedhostmovement',
            options={'verbose_name': 'host movement - clipped', 'verbose_name_plural': 'host movement - clipped'},
        ),
        migrations.AlterModelOptions(
            name='hostmovement',
            options={'verbose_name': 'host movement', 'verbose_name_plural': 'host movement'},
        ),
        migrations.AlterModelOptions(
            name='pesttreatment',
            options={'verbose_name': 'pest treatment', 'verbose_name_plural': 'pest treatment'},
        ),
        migrations.AlterField(
            model_name='weather',
            name='pest',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pops.pest', verbose_name='pest (case study specific)'),
        ),
    ]
