# Generated by Django 3.1.4 on 2021-01-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0003_auto_20210109_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='output_frequency_unit',
            field=models.CharField(choices=[('year', 'Year'), ('month', 'Month'), ('week', 'Week'), ('day', 'Day')], default='Year', help_text='Select a output frequency unit for your simulation', max_length=50, verbose_name='output frequency'),
        ),
    ]
