# Generated by Django 2.2.4 on 2019-08-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0003_auto_20190815_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pest',
            name='anthropogenic_dispersal_type',
            field=models.CharField(blank=True, choices=[('CAUCHY', 'Cauchy'), ('DOUBLE SCALE CAUCHY', 'Double Scale Cauchy'), ('EXPONENTIAL', 'Exponential'), ('DOUBLE SCALE EXPONENTIAL', 'Double Scale Exponential')], default='CAUCHY', max_length=70, null=True, verbose_name='anthropogenic dispersal type'),
        ),
        migrations.AlterField(
            model_name='pest',
            name='natural_dispersal_type',
            field=models.CharField(blank=True, choices=[('CAUCHY', 'Cauchy'), ('DOUBLE SCALE CAUCHY', 'Double Scale Cauchy'), ('EXPONENTIAL', 'Exponential'), ('DOUBLE SCALE EXPONENTIAL', 'Double Scale Exponential')], default='CAUCHY', max_length=70, null=True, verbose_name='natural dispersal type'),
        ),
    ]
