# Generated by Django 2.1.5 on 2019-05-24 19:25

from django.db import migrations, models
import pops.models


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0003_calibrationinfestation_validationinfestation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibrationinfestation',
            name='user_file',
            field=models.FileField(blank=True, help_text='Upload your calibration infestation/infection data as a raster file (1 file with a layer for each year). At least 3 years are needed for calibration and validation ', upload_to=pops.models.validation_infestation_directory, verbose_name='calibration infestation data'),
        ),
        migrations.AlterField(
            model_name='validationinfestation',
            name='user_file',
            field=models.FileField(blank=True, help_text='Upload your validation infestation/infection data as a raster file (1 file with a layer for each year). At least 3 years are needed for calibration and validation ', upload_to=pops.models.calibration_infestation_directory, verbose_name='validation infestation data'),
        ),
    ]
