# Generated by Django 2.1.5 on 2019-05-27 19:11

from django.db import migrations, models
import pops.models


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0004_auto_20190524_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lethaltemperature',
            name='lethal_temperature_data',
            field=models.FileField(help_text='Upload your letah temperature data as a raster file (1 file with a layer for each year).', null=True, upload_to=pops.models.lethal_temperature_directory, verbose_name='lethal temperature data'),
        ),
        migrations.AlterField(
            model_name='precipitation',
            name='precipitation_data',
            field=models.FileField(help_text='Upload your precipitation data as a raster file (1 file with a layer for each timestep).', null=True, upload_to=pops.models.precipitation_directory, verbose_name='precipitation data'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='temperature_data',
            field=models.FileField(help_text='Upload your temperature data as a raster file (1 file with a layer for each timestep).', null=True, upload_to=pops.models.temperature_directory, verbose_name='temperature data'),
        ),
    ]
