# Generated by Django 3.1.4 on 2021-01-11 13:33

from django.db import migrations, models
import pops.models


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0004_auto_20210111_0700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostlocation',
            old_name='host_map',
            new_name='raster_map',
        ),
        migrations.RemoveField(
            model_name='clippedhostlocation',
            name='host_map',
        ),
        migrations.AddField(
            model_name='clippedhostlocation',
            name='json_map',
            field=models.JSONField(help_text='Clipped host data (json)', null=True, verbose_name='clipped json host data'),
        ),
        migrations.AddField(
            model_name='clippedhostlocation',
            name='raster_map',
            field=models.FileField(blank=True, help_text='Clipped host data (raster)', upload_to=pops.models.clipped_host_directory, verbose_name='clipped raster host data'),
        ),
    ]
