# Generated by Django 2.2.4 on 2019-08-19 13:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0005_auto_20190815_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistanceToBoundary',
            fields=[
                ('output', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pops.Output', verbose_name='output')),
                ('west_distance', models.DecimalField(blank=True, decimal_places=2, default=1, help_text='Spread rate in westerly direction', max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='westerly spread rate')),
                ('east_distance', models.DecimalField(blank=True, decimal_places=2, default=1, help_text='Spread rate in easterly direction', max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='easterly spread rate')),
                ('north_distance', models.DecimalField(blank=True, decimal_places=2, default=1, help_text='Spread rate in northerly direction', max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='northerly spread rate')),
                ('south_distance', models.DecimalField(blank=True, decimal_places=2, default=1, help_text='Spread rate in southerly direction', max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='southerly spread rate')),
            ],
            options={
                'verbose_name': 'distance to boundary',
                'verbose_name_plural': 'distance to boundarys',
            },
        ),
    ]
