# Generated by Django 3.1.4 on 2021-01-11 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0005_auto_20210111_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='staff_approved',
            field=models.BooleanField(default=False, help_text='Is this case study available to the public.', verbose_name='approved by staff'),
        ),
        migrations.AlterField(
            model_name='pest',
            name='pest_information',
            field=models.ForeignKey(blank=True, help_text='pest information.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pops.pestinformation', verbose_name='pest information'),
        ),
        migrations.AlterField(
            model_name='pestinformation',
            name='about',
            field=models.TextField(help_text='Information about the pest including when it arrived.', verbose_name='about the pest'),
        ),
        migrations.AlterField(
            model_name='pestinformation',
            name='management_activity',
            field=models.TextField(help_text='What is being done to manage this pest.', verbose_name='management activities to control the pest'),
        ),
        migrations.AlterField(
            model_name='pestinformation',
            name='risks',
            field=models.TextField(help_text='What commodities are at risk from this pest?', verbose_name='risks associated with the pest'),
        ),
        migrations.AlterField(
            model_name='pestinformation',
            name='scientific_name',
            field=models.CharField(help_text='Pest scientific name.', max_length=150, verbose_name='pest scientific name'),
        ),
        migrations.AlterField(
            model_name='pestinformation',
            name='staff_approved',
            field=models.BooleanField(default=False, help_text='Is this case study available for the public.', verbose_name='approved by staff'),
        ),
    ]
