# Generated by Django 3.1.4 on 2021-01-12 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0006_auto_20210111_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clippedhostlocation',
            name='pest_host_interaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pops.pesthostinteraction', verbose_name='pest host interaction'),
        ),
        migrations.AlterField(
            model_name='clippedhostmovement',
            name='pest_host_interaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pops.pesthostinteraction', verbose_name='pest host interaction'),
        ),
    ]
