# Generated by Django 2.2.2 on 2019-06-10 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0006_auto_20190603_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='logging',
            field=models.TextField(blank=True, help_text='For checking error logs for backend model runs', max_length=300, null=True, verbose_name='error logs for backend'),
        ),
        migrations.AddField(
            model_name='run',
            name='management_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True, verbose_name='management area'),
        ),
        migrations.AddField(
            model_name='run',
            name='management_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True, verbose_name='management cost'),
        ),
        migrations.AddField(
            model_name='run',
            name='tangible_landscape',
            field=models.BooleanField(default=False, help_text='Use tangible landscape for management?', verbose_name='tangible landscape'),
        ),
        migrations.AddField(
            model_name='run',
            name='time_taken',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='time taken'),
        ),
        migrations.AlterField(
            model_name='run',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('IN PROGRESS', 'In progress'), ('READING DATA', 'Reading data'), ('WAITING FOR TL', 'Waiting for Tangible Landscape'), ('RUNNING MODEL', 'Running model'), ('WRITING DATA', 'Writing data'), ('FAILED', 'Failed'), ('SUCCESS', 'Successful')], default='PENDING', max_length=20, verbose_name='run status'),
        ),
    ]
