# Generated by Django 2.2.2 on 2019-06-13 12:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0007_auto_20190609_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='budget',
            field=models.PositiveIntegerField(default=30000000, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='budget'),
        ),
        migrations.AlterField(
            model_name='run',
            name='management_area',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=13, null=True, verbose_name='management area'),
        ),
        migrations.AlterField(
            model_name='run',
            name='management_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=13, null=True, verbose_name='management cost'),
        ),
        migrations.AlterField(
            model_name='run',
            name='name',
            field=models.CharField(max_length=80, verbose_name='run name'),
        ),
    ]
