# Generated by Django 2.2.4 on 2019-08-19 16:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0007_auto_20190819_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distancetoboundary',
            name='east_distance',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, help_text='Spread rate in easterly direction', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='easterly distance to boundary'),
        ),
        migrations.AlterField(
            model_name='distancetoboundary',
            name='north_distance',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, help_text='Spread rate in northerly direction', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='northerly distance to boundary'),
        ),
        migrations.AlterField(
            model_name='distancetoboundary',
            name='south_distance',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, help_text='Spread rate in southerly direction', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='southerly distance to boundary'),
        ),
        migrations.AlterField(
            model_name='distancetoboundary',
            name='west_distance',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, help_text='Spread rate in westerly direction', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='westerly distance to boundary'),
        ),
        migrations.AlterField(
            model_name='spreadrate',
            name='east_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, help_text='Spread rate in easterly direction', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='easterly spread rate'),
        ),
        migrations.AlterField(
            model_name='spreadrate',
            name='north_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, help_text='Spread rate in northerly direction', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='northerly spread rate'),
        ),
        migrations.AlterField(
            model_name='spreadrate',
            name='south_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, help_text='Spread rate in southerly direction', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='southerly spread rate'),
        ),
        migrations.AlterField(
            model_name='spreadrate',
            name='west_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, help_text='Spread rate in westerly direction', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='westerly spread rate'),
        ),
        migrations.AlterField(
            model_name='timetoboundary',
            name='east_time',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, help_text='Spread rate in easterly direction', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='easterly time to boundary'),
        ),
        migrations.AlterField(
            model_name='timetoboundary',
            name='north_time',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, help_text='Spread rate in northerly direction', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='northerly time to boundary'),
        ),
        migrations.AlterField(
            model_name='timetoboundary',
            name='south_time',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, help_text='Spread rate in southerly direction', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='southerly time to boundary'),
        ),
        migrations.AlterField(
            model_name='timetoboundary',
            name='west_time',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, help_text='Spread rate in westerly direction', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='westerly time to boundary'),
        ),
    ]
