# Generated by Django 3.1.4 on 2021-01-14 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0008_auto_20210112_1808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quarantinelink',
            options={'verbose_name': 'quarantine pest', 'verbose_name_plural': 'quarantines pest'},
        ),
    ]
