# Generated by Django 2.2.2 on 2019-06-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0008_auto_20190613_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='name',
            field=models.CharField(max_length=45, verbose_name='run name'),
        ),
    ]
