# Generated by Django 3.1.4 on 2021-01-20 14:04

from django.db import migrations, models
import pops.models


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0009_auto_20210114_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='r_data',
            field=models.FileField(blank=True, help_text='R data file to run PoPS model', upload_to=pops.models.run_r_data_directory, verbose_name='R data file'),
        ),
    ]
