# Generated by Django 2.2.2 on 2019-06-18 15:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0009_auto_20190614_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='cost_per_hectare',
        ),
        migrations.AddField(
            model_name='run',
            name='cost_per_meter_squared',
            field=models.PositiveIntegerField(default=100, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='cost per meter squared'),
        ),
    ]
