# Generated by Django 2.2.4 on 2019-08-20 01:45

import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0009_auto_20190819_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=2015, null=True, validators=[django.core.validators.MinValueValidator(1900)], verbose_name='year')),
                ('observed_data', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('case_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pops.CaseStudy', verbose_name='case study id')),
            ],
            options={
                'verbose_name': 'historic data',
                'verbose_name_plural': 'historic datas',
            },
        ),
    ]
