# Generated by Django 2.2.4 on 2019-08-20 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0010_historicdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicdata',
            old_name='observed_data',
            new_name='data',
        ),
    ]
