# Generated by Django 2.2.4 on 2019-08-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0011_auto_20190820_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='percentnaturaldistance',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='percent natural distance scale value'),
        ),
        migrations.AlterField(
            model_name='reproductiverate',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, verbose_name='reproductive rate value'),
        ),
        migrations.AlterField(
            model_name='vectorreproductiverate',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, verbose_name='vector reproductive rate value'),
        ),
    ]
