# Generated by Django 2.2.2 on 2019-06-18 19:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0011_auto_20190618_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='cost_per_meter_squared',
            field=models.DecimalField(blank=True, decimal_places=9, default=0, max_digits=14, null=True, verbose_name='cost per meter squared'),
        ),
        migrations.AlterField(
            model_name='run',
            name='final_year',
            field=models.PositiveIntegerField(default=2021, null=True, validators=[django.core.validators.MinValueValidator(2018)], verbose_name='final run year'),
        ),
    ]
