# Generated by Django 3.1.4 on 2021-01-22 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0011_auto_20210122_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latencyperiod',
            name='maximum',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Maximum latency period (in days)', null=True, verbose_name='maximum days'),
        ),
    ]
