# Generated by Django 2.2.4 on 2019-08-26 20:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0012_auto_20190820_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicdata',
            name='infected_area',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, help_text='Overall infected area from the run.', max_digits=16, validators=[django.core.validators.MinValueValidator(0)], verbose_name='infected_area (m^2)'),
        ),
        migrations.AlterField(
            model_name='spreadrate',
            name='east_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Spread rate in easterly direction', max_digits=6, null=True, verbose_name='easterly spread rate'),
        ),
        migrations.AlterField(
            model_name='spreadrate',
            name='north_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Spread rate in northerly direction', max_digits=6, null=True, verbose_name='northerly spread rate'),
        ),
        migrations.AlterField(
            model_name='spreadrate',
            name='south_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Spread rate in southerly direction', max_digits=6, null=True, verbose_name='southerly spread rate'),
        ),
        migrations.AlterField(
            model_name='spreadrate',
            name='west_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Spread rate in westerly direction', max_digits=6, null=True, verbose_name='westerly spread rate'),
        ),
    ]
