# Generated by Django 2.2.2 on 2019-06-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0012_auto_20190618_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='management_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='management cost'),
        ),
    ]
