# Generated by Django 3.1.4 on 2021-01-22 21:45

from django.db import migrations, models
import pops.models


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0012_auto_20210122_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allpopulationsdata',
            name='user_file',
            field=models.FileField(blank=True, help_text='Upload your total population data as a raster file. This could be all the plants or animals in a cell, or alternatively, all  cells could have the value of the maximum number of hosts found in any cell in your study area.', upload_to=pops.models.all_populations_directory, verbose_name='all populations data'),
        ),
    ]
