# Generated by Django 3.1.4 on 2021-01-28 16:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0013_auto_20210122_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperaturereclass',
            name='max_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum temperature (in degrees Celsius) to reclass from', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)], verbose_name='max'),
        ),
    ]
