# Generated by Django 2.2.3 on 2019-07-27 18:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0013_auto_20190621_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='management_month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=7, help_text='What month does management take place?', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='month management takes place'),
        ),
    ]
