# Generated by Django 2.2.4 on 2019-08-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0014_output_susceptible_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spreadrate',
            name='east_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Spread rate in easterly direction', max_digits=16, null=True, verbose_name='easterly spread rate'),
        ),
        migrations.AlterField(
            model_name='spreadrate',
            name='north_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Spread rate in northerly direction', max_digits=16, null=True, verbose_name='northerly spread rate'),
        ),
        migrations.AlterField(
            model_name='spreadrate',
            name='south_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Spread rate in southerly direction', max_digits=16, null=True, verbose_name='southerly spread rate'),
        ),
        migrations.AlterField(
            model_name='spreadrate',
            name='west_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Spread rate in westerly direction', max_digits=16, null=True, verbose_name='westerly spread rate'),
        ),
    ]
