# Generated by Django 3.1.4 on 2021-01-31 12:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0016_auto_20210128_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapboxparameters',
            name='zoom',
            field=models.PositiveSmallIntegerField(blank=True, default=7, help_text='The zoom level of MapBox', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(22)], verbose_name='mapbox zoom level'),
        ),
    ]
