# Generated by Django 3.1.4 on 2021-02-01 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0017_auto_20210131_0711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='output',
            old_name='susceptible_map',
            new_name='standard_deviation_map',
        ),
    ]
