# Generated by Django 2.2.4 on 2019-09-06 03:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0017_historicdata_number_infected'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='max_value',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Maximum value of number of infected in a cell for final year of the default run', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='maximum value within a cell in default run'),
        ),
    ]
