# Generated by Django 3.1.4 on 2021-02-01 23:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0018_auto_20210201_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pesticide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_name', models.CharField(max_length=150, verbose_name='pesticide common or trade name')),
                ('duration', models.DecimalField(blank=True, decimal_places=2, default=14, help_text='Average duration in days', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(365)], verbose_name='duration')),
                ('cost_per_meter_squared', models.DecimalField(blank=True, decimal_places=2, default=10, help_text='Average cost per meter squared (in $US)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='average cost per meter squared')),
            ],
            options={
                'verbose_name': 'pesticide',
                'verbose_name_plural': 'pesticides',
            },
        ),
        migrations.CreateModel(
            name='PestPesticideLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('efficacy', models.DecimalField(decimal_places=4, default=0.9, help_text='Efficacy of the pesticide for the given pest (range 0-1)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='efficacy')),
                ('pest_information', models.ForeignKey(help_text='pest information.', on_delete=django.db.models.deletion.CASCADE, to='pops.pestinformation', verbose_name='pest information')),
                ('pesticide', models.ForeignKey(help_text='pesticide', on_delete=django.db.models.deletion.CASCADE, to='pops.pesticide', verbose_name='pesticide')),
            ],
            options={
                'verbose_name': 'pest pesticide link',
                'verbose_name_plural': 'pest pesticide links',
            },
        ),
    ]
