# Generated by Django 3.0 on 2020-01-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0018_session_max_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runcollection',
            name='name',
            field=models.CharField(default='Default_name', max_length=45, verbose_name='run name'),
        ),
    ]
