# Generated by Django 3.1.4 on 2021-02-02 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0019_pesticide_pestpesticidelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='mean_spread_map',
            field=models.JSONField(null=True),
        ),
    ]
