# Generated by Django 3.0.2 on 2020-02-07 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0019_auto_20200131_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='public',
            field=models.BooleanField(default=False, help_text='Is the session sharing set to public (any user can view and edit the session)?', verbose_name='public'),
        ),
    ]
