# Generated by Django 3.1.6 on 2021-02-24 18:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0020_output_mean_spread_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesticide',
            name='cost_per_meter_squared',
            field=models.DecimalField(blank=True, decimal_places=5, default=10, help_text='Average cost per meter squared (in $US)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='average cost per meter squared'),
        ),
    ]
