# Generated by Django 3.0 on 2020-03-18 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0020_session_public'),
        ('pops', '0019_auto_20200114_1637'),
    ]

    operations = [
    ]
