# Generated by Django 3.0.4 on 2020-04-05 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0019_auto_20200114_1637'),
        ('pops', '0020_session_public'),
    ]

    operations = [
    ]
