# Generated by Django 3.0.5 on 2020-09-21 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0021_merge_20200405_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pest',
            name='pest_information',
            field=models.ForeignKey(blank=True, help_text='Sample help text.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pops.PestInformation', verbose_name='pest information'),
        ),
    ]
