# Generated by Django 3.1.1 on 2020-09-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0022_auto_20200318_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicdata',
            name='data',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='hostdata',
            name='host_map',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='output',
            name='probability_map',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='output',
            name='single_spread_map',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='output',
            name='susceptible_map',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='management_polygons',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
