# Generated by Django 3.2.3 on 2021-06-22 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0022_alter_casestudy_r_data'),
        ('pops', '0022_plottingdistancescale_plottingreproductiverate'),
    ]

    operations = [
    ]
