# Generated by Django 3.2.3 on 2021-06-22 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0023_merge_20210622_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plottingreproductiverate',
            name='parameters',
        ),
        migrations.DeleteModel(
            name='PlottingDistanceScale',
        ),
        migrations.DeleteModel(
            name='PlottingReproductiveRate',
        ),
    ]
