# Generated by Django 3.2.5 on 2022-01-16 19:02

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import pops.models


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0024_auto_20210622_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlottingDistanceScale',
            fields=[
                ('parameters', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pops.parameters', verbose_name='parameters')),
                ('values', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)]), blank=True, help_text='Distance scale values', size=None, verbose_name='distance scale values')),
                ('probabilities', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=3, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]), blank=True, help_text='Distance scale probabilities', size=None, verbose_name='distance scale probabilities')),
                ('minimum', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum value in the array', max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='minimum')),
                ('maximum', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum value in the array', max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='maximum')),
                ('most_probable_value', models.DecimalField(blank=True, decimal_places=2, help_text='Value in the array with the highest probability', max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='most probable value')),
                ('step_size', models.DecimalField(blank=True, decimal_places=2, help_text='Step size for the array', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='step size')),
            ],
            options={
                'verbose_name': 'distance scale parameters for plotting',
                'verbose_name_plural': 'distance scale parameters for plotting',
            },
        ),
        migrations.CreateModel(
            name='PlottingReproductiveRate',
            fields=[
                ('parameters', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pops.parameters', verbose_name='parameters')),
                ('values', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)]), blank=True, help_text='Reproductive rate values', size=None, verbose_name='reproductive rate values')),
                ('probabilities', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=3, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]), blank=True, help_text='Reproductive rate probabilities', size=None, verbose_name='reproductive rate probabilities')),
                ('minimum', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum value in the array', max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='minimum')),
                ('maximum', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum value in the array', max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='maximum')),
                ('most_probable_value', models.DecimalField(blank=True, decimal_places=2, help_text='Value in the array with the highest probability', max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='most probable value')),
                ('step_size', models.DecimalField(blank=True, decimal_places=2, help_text='Step size for the array', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='step size')),
            ],
            options={
                'verbose_name': 'reproductive rate parameters for plotting',
                'verbose_name_plural': 'reproductive rate parameters for plotting',
            },
        ),
        migrations.AddField(
            model_name='pesticide',
            name='default_application_day',
            field=models.IntegerField(blank=True, default=1, help_text='Default day for pesticide application (1-31)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='default day of pesticide application'),
        ),
        migrations.AddField(
            model_name='pesticide',
            name='default_application_month',
            field=models.IntegerField(blank=True, default=4, help_text='Default month for pesticide application (1-12)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='default month of pesticide application'),
        ),
        migrations.AlterField(
            model_name='run',
            name='r_data',
            field=models.FileField(blank=True, help_text='R data file to run PoPS model', null=True, upload_to=pops.models.run_r_data_directory, verbose_name='R data file'),
        ),
    ]
