# Generated by Django 3.1.1 on 2020-09-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0024_auto_20200903_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='pestinformation',
            name='large_image',
            field=models.FileField(blank=True, help_text='Upload image of pest/pathogen (crop to 2in square at 72ppi).', null=True, upload_to='pest_images', verbose_name='Large image of pest/pathogen'),
        ),
        migrations.AddField(
            model_name='pestinformation',
            name='spread_image',
            field=models.FileField(blank=True, help_text='Upload image or gif of pest/pathogen ( at 72ppi).', null=True, upload_to='pest_images', verbose_name='Image or GIF of forecast'),
        ),
        migrations.AlterField(
            model_name='pestinformation',
            name='host_type',
            field=models.CharField(choices=[('ANIMAL', 'Animal'), ('PLANT', 'Plant')], default='PLANT', help_text='Choose what system type this pest/pathogen infects.', max_length=30, verbose_name='host type'),
        ),
        migrations.AlterField(
            model_name='pestinformation',
            name='organism_type',
            field=models.CharField(choices=[('PEST', 'Pest (e.g. insect)'), ('PATHOGEN', 'Pathogen (e.g. disease)')], default='PEST', help_text='Choose whether this is a pest or pathogen.', max_length=30, verbose_name='organism type'),
        ),
        migrations.AlterField(
            model_name='pestinformation',
            name='thumbnail',
            field=models.FileField(blank=True, help_text='Upload thumbnail image of pest/pathogen (58x58 px crop to 0.8in square at 72ppi).', null=True, upload_to='pest_images', verbose_name='Small thumbnail image of pest/pathogen'),
        ),
    ]
