# Generated by Django 3.2.5 on 2022-01-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0025_auto_20220116_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesticide',
            name='default_application_month',
            field=models.CharField(choices=[('01', 'January'), ('02', 'February'), ('03', 'March'), ('04', 'April'), ('05', 'May'), ('06', 'June'), ('07', 'July'), ('08', 'August'), ('09', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], default='04', help_text='Default month for pesticide application (1-12)', max_length=2, verbose_name='default month of pesticide application'),
        ),
    ]
