# Generated by Django 3.1.1 on 2020-09-23 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0026_auto_20200907_1408'),
        ('pops', '0022_auto_20200921_0654'),
    ]

    operations = [
    ]
