# Generated by Django 3.1.1 on 2020-09-23 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0027_merge_20200923_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runcollection',
            name='cost_per_meter_squared',
        ),
        migrations.RemoveField(
            model_name='runcollection',
            name='efficacy',
        ),
    ]
