# Generated by Django 4.0.1 on 2022-01-28 18:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0027_alter_pesticide_default_application_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesticide',
            name='default_application_day',
        ),
        migrations.RemoveField(
            model_name='pesticide',
            name='default_application_month',
        ),
        migrations.AddField(
            model_name='pestpesticidelink',
            name='application_efficacy',
            field=models.DecimalField(decimal_places=4, default=0.9, help_text='Efficacy of the application of pesticide for the given pest (range 0-1)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='application efficacy'),
        ),
        migrations.AddField(
            model_name='pestpesticidelink',
            name='default_application_day',
            field=models.IntegerField(blank=True, default=1, help_text='Default day for pesticide application (1-31) for the given pest', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='default day of pesticide application'),
        ),
        migrations.AddField(
            model_name='pestpesticidelink',
            name='default_application_month',
            field=models.IntegerField(blank=True, default=4, help_text='Default month for pesticide application (1-12) for the given pest', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='default month of pesticide application'),
        ),
        migrations.AddField(
            model_name='session',
            name='default_host_removal_month',
            field=models.IntegerField(blank=True, default=4, help_text='Default month for host removal (1-12)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='default month of host removal'),
        ),
        migrations.AddField(
            model_name='session',
            name='default_removal_day',
            field=models.IntegerField(blank=True, default=1, help_text='Default day for host removal (1-31) host removal', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='default day of host removal'),
        ),
    ]
