# Generated by Django 3.1.2 on 2020-10-16 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0027_merge_20200921_0954'),
        ('pops', '0028_auto_20200923_1032'),
    ]

    operations = [
    ]
