# Generated by Django 4.0.1 on 2022-01-28 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0028_remove_pesticide_default_application_day_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='default_removal_day',
            new_name='default_host_removal_day',
        ),
    ]
