# Generated by Django 4.0.1 on 2022-02-05 02:15

from django.db import migrations, models
import pops.models


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0029_rename_default_removal_day_session_default_host_removal_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='advanced_network_file',
            field=models.FileField(blank=True, help_text='Advanced network file', null=True, upload_to=pops.models.advanced_network_file_directory, verbose_name='Advanced network file'),
        ),
    ]
