# Generated by Django 3.1.1 on 2020-10-08 16:56

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import pops.models


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0030_auto_20201006_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointDataFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_file', models.FileField(blank=True, help_text='Upload your OGR-supported geospatial file', upload_to=pops.models.shapefile_directory, verbose_name='geospatial file')),
            ],
        ),
        migrations.AlterField(
            model_name='point',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326, verbose_name='point'),
        ),
    ]
