# Generated by Django 4.0.1 on 2022-02-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0030_casestudy_advanced_network_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pest',
            name='anthropogenic_dispersal_type',
            field=models.CharField(blank=True, choices=[('CAUCHY', 'Cauchy'), ('DOUBLE SCALE CAUCHY', 'Double Scale Cauchy'), ('EXPONENTIAL', 'Exponential'), ('DOUBLE SCALE EXPONENTIAL', 'Double Scale Exponential'), ('NETWORK', 'Network')], default='CAUCHY', max_length=70, verbose_name='anthropogenic dispersal type'),
        ),
    ]
