# Generated by Django 4.0.1 on 2022-03-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0031_alter_pest_anthropogenic_dispersal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='output',
            name='max_spread_map',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='output',
            name='mean_spread_map',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='output',
            name='median_spread_map',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='output',
            name='min_spread_map',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='output',
            name='probability_map',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='output',
            name='standard_deviation_map',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
