# Generated by Django 4.0.1 on 2022-03-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0032_alter_output_max_spread_map_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('IN PROGRESS', 'In progress'), ('READING DATA', 'Reading data'), ('WAITING FOR TL', 'Waiting for Tangible Landscape'), ('RUNNING MODEL', 'Running model'), ('WRITING DATA', 'Writing data'), ('FAILED', 'Failed'), ('SUCCESS', 'Successful'), ('WRITING_R_DATA', 'Writing R data'), ('R_DATA_SUCCESS', 'R data written successfully')], default='PENDING', max_length=20, verbose_name='run status'),
        ),
    ]
