# Generated by Django 4.0.1 on 2022-11-14 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0033_alter_run_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='default_management_type',
            field=models.CharField(choices=[('HOST_REMOVAL', 'Host removal'), ('PESTICIDE', 'Pesticide')], default='PESTICIDE', help_text='What will be the predominant management type? (This can be modified in the session.)', max_length=30, verbose_name='default management type'),
        ),
    ]
